### ISSUE TITLE
EDL generation for Kodi

### ISSUE THREAD

**Issue by Dnkhatri** [nielstenboom/recurring-content-detector#11]
Your project matches exactly what I have been hoping kodi upnext addon devs would implement. But they feel intro and outro detection is not good enough for them to implement those features. Would it be possible for your app to create edl timing files. 
 
https://github.com/im85288/service.upnext/issues/171

**Comment by nielstenboom** [comment]
Hi! Cool that your project matches a neat use case.

I don't think generating EDL files really falls into the scope of this project. However I think generating these files using my project is quite straightforward.

You could do something like this:
```python
import recurring_content_detector as rcd

results = rcd.detect("videos")

for filename, detections in results.items():
    print(f"EDL for {filename}:")
    for start,end in detections:
        print(f"{start}\t{end}\t3")
    print("\n")
```
And you'd get the following output (depending on the videos you gave as input):
```
EDL for episode1.mp4:
366.1	417.7	3
101.16	123.6	3


EDL for episode2.mp4:
0.0	75.36	3
228.35	279.7	3
```

I don't know anything about EDL files so I picked the `action=3 (commercial break)` as is described here (https://kodi.wiki/view/Edit_decision_list#MPlayer_EDL). This is subject to change of course. Would this fit your needs?

**Comment by Dnkhatri** [comment]
Yes partially though the edl definitions haven't been set yet for intro credits and outro credits. These are the basic definitions. What you are suggesting would work with the current definitions. 

0 - Cut

1 - Mute

2 - Scene Marker (if start and end times are specified, the end time is used)

3 - Commercial Break

4 - intro (proposed)

5 - outro end credits (proposed)

**Comment by nielstenboom** [comment]
Ah yes it should definitely be possible to generate EDL files containing the new proposed definitions using my project! But then this project would have to be integrated somewhere into a kodi addon that actually runs the similar code I mentioned in my previous comment.

**Comment by nielstenboom** [comment]
I'm going to close this issue, as EDL generation is not something that will be embedded into this project. If you need further guidance on how to generate them using my project though, feel free to keep commenting on this thread 👍
