### ISSUE TITLE
Question: Can a new video be queried against the existing video files

### ISSUE THREAD

**Issue by saket1999** [nielstenboom/recurring-content-detector#30]
For example

When 10 episodes were present, the script was executed and we get all the timestamp for 10 episodes but when a new episode is downloaded, is it possible to match it against the previous 10 episode without repeating the process for first 10 episodes.

**Comment by nielstenboom** [comment]
Hey @saket1999. The code already does this for you, if it processes a video for the first time, it will store the vectors in a pickle file (you can change the file location of this by setting the `artifacts_dir` parameter, by default it will store it in the same directory as the videos), then if it has to run detection again, it will look for pickle files first, if they exist then the video will not be re-processed and the process will be much faster.
