### ISSUE TITLE
Make it a pypi package

### ISSUE THREAD

**Issue by Impre-visible** [nielstenboom/recurring-content-detector#33]
Hi, I want to use this tool, on windows and linux, is it possible to have a package for windows where all the library are working, and same for linux ? I can't install faiss

**Comment by nielstenboom** [comment]
Awesome to hear you'd like to use this tool!

> is it possible to have a package for windows where all the library are working, and same for linux ?

I'm sorry but this is not as straightforward as it sounds. The Faiss installation is quite complex and will be hard to package into a pypi package (https://github.com/facebookresearch/faiss/blob/main/INSTALL.md). I recommend to install it via conda.

> I can't install faiss

Can you provide some more details why you can't install it?

**Comment by nielstenboom** [comment]
Turned out it wasn't too hard after all, the latest version can be installed + used solely via pip!
